# Generated by Django 4.1.4 on 2023-02-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_getimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetImage',
        ),
    ]
