# Generated by Django 4.1.4 on 2023-02-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_getimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
